version: '3'

services:

  streamer:
    container_name: lp-detection-streamer
    build:
      context: streamer
      dockerfile: Dockerfile
    devices:
      - "/dev/vchiq"
    ports:
      - "8080:80"
    restart: unless-stopped

  openalpr:
    container_name: lp-detection-openalpr
    build:
      context: openalpr
      dockerfile: Dockerfile-armv6
    volumes:
      - ./openalpr/data:/data
    depends_on:
      - streamer
      - control
    restart: unless-stopped

  control:
    container_name: lp-detection-control
    build:
      context: control
      dockerfile: Dockerfile-armv6
    ports:
      - "80"
