version: '3'

services:

  streamer:
    container_name: lp-detection-streamer
    build: ./streamer
    image: abarruda/license-plate-reader_streamer
    devices:
      - "/dev/vchiq"
    ports:
      - "8081:80"
    restart: unless-stopped

  openalpr:
    container_name: lp-detection-openalpr
    build:
      context: openalpr
      dockerfile: Dockerfiles/Dockerfile
    image: abarruda/license-plate-reader_openalpr
    volumes:
      - ./openalpr/data:/data
      - ./openalpr/alprd.conf:/etc/openalpr/alprd.conf
    depends_on:
      - streamer
      - control
    restart: unless-stopped

  control:
    container_name: lp-detection-control
    build: ./control
    image: abarruda/license-plate-reader_control
    ports:
      - "80"
